/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.company2566;

import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Arthit LungYa
 */
public class TableTest extends javax.swing.JFrame {

    /**
     * Creates new form TableTest
     */
    DefaultTableModel tableModel = new DefaultTableModel();

    public TableTest() {
        initComponents();
        Object[] header = {"itemCode", "itemName", "price", "qty", "amount"};
        // tableModel.setColumnIdentifiers(header);
        // tableModel.setColumnCount(5);
        dataTable.setModel(tableModel);
        // initialValue();
        Object[][] data = {{"0001", "GPU", "30000", "50", null},
        {"0002", "Monitor", "30000", "50", null},
        {"0003", "SSD", "30000", "50", null},
        {"0004", "RAM", "30000", "50", null},
        {"0005", "CPU", "30000", "50", null}};
        tableModel.setDataVector(data, header);
        amount.doClick();
        sumTotal.doClick();
    }

    public void initialValue() {
        Object[] data = {"0001", "GPU", "30000", "50", null};
        tableModel.addRow(data);
        Object[] data_1 = {"0002", "Monitor", "30000", "50", null};
        tableModel.addRow(data_1);
        Object[] data_2 = {"0003", "SSD", "30000", "50", null};
        tableModel.addRow(data_2);
        Object[] data_3 = {"0004", "RAM", "30000", "50", null};
        tableModel.addRow(data_3);
        Object[] data_4 = {"0005", "CPU", "30000", "50", null};
        tableModel.addRow(data_4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        showButton = new javax.swing.JButton();
        Total1 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        sumTotal = new javax.swing.JButton();
        amount = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        itemName = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        amount_box = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"001", "PC", "50000", "5", null},
                {"002", "Phone", "13000", "15", null},
                {"003", "Bike", "5000", "33", null},
                {"004", "Candy", "3", "100", null},
                {"005", "Water", "10", "100", null}
            },
            new String [] {
                "itemCode", "itemName", "Price", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(dataTable);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(1).setPreferredWidth(130);
        }

        showButton.setText("Show");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        Total1.setText("Total");

        sumTotal.setText("Total");
        sumTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumTotalActionPerformed(evt);
            }
        });

        amount.setText("Amount");
        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("ItemCode");

        jLabel2.setText("Price");

        jLabel3.setText("ItemName");

        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priceKeyPressed(evt);
            }
        });

        jLabel4.setText("Qty");

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
        });

        jLabel5.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(amount_box, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(showButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Total1)
                                .addGap(18, 18, 18)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sumTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(addButton)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(amount)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(amount_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showButton)
                    .addComponent(Total1)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumTotal))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            qty.requestFocus();
            calculateAmount_box();
        }
    }//GEN-LAST:event_priceKeyPressed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            qty.requestFocus();
            calculateAmount_box();
        }
    }//GEN-LAST:event_qtyKeyPressed

    private void calculateAmount_box() {
        try {
            int priceValue = Integer.parseInt(price.getText());
            int qtyValue = Integer.parseInt(qty.getText());
            int Total = priceValue * qtyValue;
            amount_box.setText(String.valueOf(Total));
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_showButtonActionPerformed
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            for (int j = 0; j < dataTable.getColumnCount(); j++) {
                System.out.print(dataTable.getValueAt(i, j) + "\t");
            }
            System.out.println();
        }
    }// GEN-LAST:event_showButtonActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_amountActionPerformed
        calculateAmount();
    }// GEN-LAST:event_amountActionPerformed

    private void sumTotalActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sumTotalActionPerformed
        calculateTotal();
    }// GEN-LAST:event_sumTotalActionPerformed

    @SuppressWarnings("empty-statement")
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addButtonActionPerformed
        calculateThis();
    }// GEN-LAST:event_addButtonActionPerformed

    private void calculateThis() {
        Object[] data = {itemCode.getText(), itemName.getText(), price.getText(), qty.getText(), amount_box.getText()};
        tableModel.addRow(data);
        int sum = Integer.parseInt(Total.getText().replace(",", ""));
        sum += Integer.parseInt(amount_box.getText().replace(",", ""));
//        int Value1 = Integer.parseInt(Total.getText());
//        int Value2 = Integer.parseInt(amount_box.getText());
//         int amountValue = Value1 + Value2;
        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
        Total.setText(numberFormat.format(sum));
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            try {
//             int value1 = (int) jTable1.getValueAt(i, 3);
//             int value2 = (int) jTable1.getValueAt(i, 2);
                int value1 = Integer.parseInt(dataTable.getValueAt(i, 3).toString());
                int value2 = Integer.parseInt(dataTable.getValueAt(i, 2).toString());
                // Calculate the subtotal and format it
                int subtotal = value1 * value2;
//                Total.setText(String.valueOf(Value1 + Value2));
//                String formattedSubtotal = numberFormat.format(subtotal);
//                jTable1.setValueAt(formattedSubtotal, i, 4);
                dataTable.setValueAt(numberFormat.format(subtotal), i, 4);
//                  jTable1.setValueAt(value1*value2, i, 4);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    private void calculateAmount() {
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            try {
                int price = Integer.parseInt(dataTable.getValueAt(i, 2).toString());
                int qty = Integer.parseInt(dataTable.getValueAt(i, 3).toString());
                int subtotal = price * qty;
                NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
                dataTable.setValueAt(numberFormat.format(subtotal), i, 4);
//                dataTable.setValueAt(subtotal, i, 4);
            } catch (Exception ex) {
            }
        }
    }

    private void calculateTotal() {
        int totalSum = 0;
        for (int i = 0; i < dataTable.getRowCount(); i++) {
            try {
                int totalValue = Integer.parseInt(dataTable.getValueAt(i, 4).toString().replaceAll(",", ""));
                totalSum += totalValue;
            } catch (Exception ex) {
            }
        }
        Total.setText(NumberFormat.getInstance(Locale.US).format(totalSum));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Total;
    private javax.swing.JLabel Total1;
    private javax.swing.JButton addButton;
    private javax.swing.JButton amount;
    private javax.swing.JTextField amount_box;
    private javax.swing.JTable dataTable;
    private javax.swing.JTextField itemCode;
    private javax.swing.JTextField itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price;
    private javax.swing.JTextField qty;
    private javax.swing.JButton showButton;
    private javax.swing.JButton sumTotal;
    // End of variables declaration//GEN-END:variables
}
